#!/bin/bash

figlet -w 120 Running clippy checker

cargo test
if [ $? -ne 0 ]; then
  figlet -w 120 Tests Failed
  exit 1
else
  figlet -w 120 Tests Passed
fi

printf "\n"

cargo clippy --all --all-targets -- -D warnings
if [ $? -ne 0 ]; then
  figlet -w 120 Time to clean up
  exit 1
else
  figlet -w 120 Clean!
fi

