#!/bin/bash
clear

figlet -w 120 Running tests

cargo test
if [ $? -ne 0 ]; then
  figlet -w 120 Tests Failed
  exit 1
else
  figlet -w 120 Tests Passed
fi

printf "\n"

figlet -w 120 Running clippy checker

cargo clippy --all --all-targets -- -D warnings -D clippy::pedantic
if [ $? -ne 0 ]; then
  figlet -w 120 Clippy issues to Fix
  exit 1
# else
#   figlet -w 120 Clean!
fi

printf "\n"

figlet -w 120 Running style checker

cargo fmt --check
if [ $? -ne 0 ]; then
  figlet -w 120 Style issues to Fix
  exit 1
else
  figlet -w 120 Clean!
fi

