#!/bin/bash

# https://doc.rust-lang.org/rustc/instrument-coverage.html
# https://llvm.org/docs/CommandGuide/llvm-cov.html#llvm-cov-show

LLVM_PROFILE_FILE=coverage/cov-%p-%m.profraw RUSTFLAGS="-C instrument-coverage" cargo test
llvm-profdata merge -sparse coverage/cov-*.profraw -o coverage/json5format.profdata

# Note that the 'cargo test' block below uses the --no-run option.
# This is just getting the list of objects to report on.
llvm-cov show \
    $( \
      for file in \
        $( \
          RUSTFLAGS="-C instrument-coverage" \
            cargo test --tests --no-run --message-format=json \
              | jq -r "select(.profile.test == true) | .filenames[]" \
              | grep -v dSYM - \
        ); \
      do \
        printf "%s %s " -object $file; \
      done \
    ) \
    --instr-profile=coverage/json5format.profdata \
    --summary-only \
    --show-instantiations --show-line-counts-or-regions \
    --Xdemangler=rustfilt \
    --ignore-filename-regex='/.cargo/registry' \
    --ignore-filename-regex='library/std/src' \
    --format=html --output-dir=coverage
    # and/or other options

wslview coverage/index.html

